import path from "path";
import { detectStack } from "../detect/detect";
import { buildExcludeList, readDirectoryTree } from "../utils/fs.js";
import { detectAPIRoutes } from "../detect/apiRoutes";
import { detectProjectMetadata } from "../detect/projectMetadata";

export async function buildReadmeContext(root: string) {
  const metadata = await detectProjectMetadata(root);

  const exclude = buildExcludeList(root);
  const structure = readDirectoryTree(root, 3, exclude);
  const limitedStructure = structure.split("\n").slice(0, 200).join("\n");

  const stack = await detectStack(root);

  const apis = detectAPIRoutes(root, metadata?.language || stack.language);

  return {
    name: metadata?.name,
    description: metadata?.description || "Generated by Commitra AI",
    structure: limitedStructure,
    stack,
    dependencies: metadata?.dependencies.slice(0, 20),
    apis,
  };
}

export async function buildApiContext(root: string) {
  const meta = await detectProjectMetadata(root);

  const name = meta.name || path.basename(root);

  const exclude = buildExcludeList(root);

  const structureFull = readDirectoryTree(root, 3, exclude);
  const structure = structureFull.split("\n").slice(0, 200).join("\n");

  const stack = await detectStack(root);

  const apis = detectAPIRoutes(root, stack.language);

  return {
    name,
    structure,
    stack,
    apis,
  };
}

export async function buildDiagramContext(root: string, depth = 3) {
  const meta = await detectProjectMetadata(root);

  const name = String(meta.name || path.basename(root));
  const description =
    String(meta.description || "An app analyzed by Commitra.");

  const exclude = buildExcludeList(root);

  const structureFull = readDirectoryTree(root, depth, exclude);
  const structure = structureFull.split("\n").slice(0, 400).join("\n");

  const stack = await detectStack(root);

  const apis = detectAPIRoutes(root, stack.language);

  return {
    root,
    name,
    description,
    structure,
    stack,
    apis,
    depth,
  };
}